"""Parse calculator expressions without executing Python input."""

from __future__ import annotations

import ast
import math
import re

import sympy as sp

MAX_EXPRESSION_LENGTH = 512
MAX_KEYS = 128


class EvalError(ValueError):
    pass


TOKEN = re.compile(
    r"\s*(\d+(?:\.\d*)?(?:[eE][+-]?\d+)?|\.\d+(?:[eE][+-]?\d+)?|[A-Za-z_][A-Za-z_0-9]*|\*\*|[+\-*/(),!])"
)
FUNCTIONS = {
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "sinh",
    "cosh",
    "tanh",
    "asinh",
    "acosh",
    "atanh",
    "ln",
    "log",
    "exp",
    "sqrt",
    "root",
    "abs",
    "factorial",
    "ncr",
    "npr",
    "rand",
    "randint",
    "lcm",
    "gcd",
    "round",
    "iPart",
    "fPart",
    "int",
    "min",
    "max",
    "mod",
    "conj",
    "real",
    "imag",
    "angle",
    "deg",
    "rad",
    "grad",
    "polar",
    "rx",
    "ry",
    "pr",
    "pt",
    "square",
    "inverse",
    "percent",
    "det",
    "transpose",
    "ref",
    "rref",
    "DotP",
    "CrossP",
    "norm",
}


def normalize(expression: str) -> str:
    expression = expression.strip()
    if not expression or len(expression) > MAX_EXPRESSION_LENGTH:
        raise EvalError(f"Enter an expression of 1–{MAX_EXPRESSION_LENGTH} characters")
    expression = re.sub(r"\[(A|B|C|Ans|I2|I3|u|v|w)\]", r"array_\1", expression)
    expression = re.sub(
        r"(\d+)\s*n(Cr|Pr)\s*(\d+)",
        lambda m: f"n{m[2].lower()}({m[1]},{m[3]})",
        expression,
    )
    for glyph, ascii_token in [
        ("×", "*"),
        ("÷", "/"),
        ("−", "-"),
        ("π", " pi "),
        ("ᴇ", "*10**"),
        ("⁻¹", " __inverse__ "),
        ("²", " __square__ "),
        ("⁻", "-"),
        ("√", "sqrt"),
        ("^", "**"),
        ("%", " __percent__ "),
    ]:
        expression = expression.replace(glyph, ascii_token)
    tokens = []
    pos = 0
    while pos < len(expression):
        match = TOKEN.match(expression, pos)
        if match is None:
            if expression[pos:].isspace():
                break
            raise EvalError("Unsupported character in expression")
        tokens.append(match[1])
        pos = match.end()

    # Postfix factorial applies to a number, constant, or complete function call.
    expanded = []
    for token in tokens:
        postfix = {
            "!": "factorial",
            "__inverse__": "inverse",
            "__square__": "square",
            "__percent__": "percent",
        }
        if token not in postfix:
            expanded.append(token)
            continue
        if not expanded:
            raise EvalError("Factorial needs an operand")
        start = len(expanded) - 1
        if expanded[start] == ")":
            depth = 1
            start -= 1
            while start >= 0:
                depth += (expanded[start] == ")") - (expanded[start] == "(")
                if depth == 0:
                    break
                start -= 1
            if start < 0:
                raise EvalError("Unbalanced parentheses")
            if start and expanded[start - 1] in FUNCTIONS:
                start -= 1
        elif not (expanded[start][0].isalnum() or expanded[start][0] == "."):
            raise EvalError("Factorial needs an operand")
        expanded[start:] = [postfix[token], "(", *expanded[start:], ")"]

    output = []
    for token in expanded:
        if output:
            prev = output[-1]
            left_atom = prev == ")" or prev[0].isalnum() or prev[0] == "."
            right_atom = token == "(" or token[0].isalnum() or token[0] == "."
            if left_atom and right_atom and not (prev in FUNCTIONS and token == "("):
                if (prev[0].isdigit() or prev[0] == ".") and (
                    token[0].isdigit() or token[0] == "."
                ):
                    raise EvalError("Missing operator between numbers")
                output.append("*")
        output.append(token)
    return " ".join(output)


def evaluate(
    expression: str,
    *,
    angle: str,
    ans: sp.Expr,
    memory: dict[str, str],
    variables: dict[str, sp.Expr] | None = None,
    classic: bool = False,
    complex_format: str = "REAL",
    rng=None,
) -> sp.Expr:
    source = normalize(expression)
    try:
        tree = ast.parse(source, mode="eval")
    except (SyntaxError, RecursionError) as exc:
        raise EvalError("Invalid expression or unbalanced parentheses") from exc
    if sum(1 for _ in ast.walk(tree)) > 256:
        raise EvalError("Expression is too complex")
    constants = {"pi": sp.pi, "e": sp.E, "i": sp.I, "ans": ans}
    # Values in memory are generated by this parser, never arbitrary Python.
    constants.update({name: sp.sympify(value) for name, value in memory.items()})
    constants.update(variables or {})
    scale = {"DEG": sp.pi / 180, "RAD": sp.S.One, "GRAD": sp.pi / 200}[angle]

    def bounded_integer(value, label, maximum=1000):
        if value.is_Integer is not True or not 0 <= value <= maximum:
            raise EvalError(f"{label} must be an integer from 0 to {maximum}")
        return int(value)

    def walk(node):
        if isinstance(node, ast.Constant) and type(node.value) in (int, float):
            literal = ast.get_source_segment(source, node)
            if len(literal) > 100 or (
                isinstance(node.value, float) and not math.isfinite(node.value)
            ):
                raise EvalError("Number is too large")
            return sp.Rational(literal)
        if isinstance(node, ast.Name) and node.id in constants:
            return constants[node.id]
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
            value = walk(node.operand)
            return -value if isinstance(node.op, ast.USub) else value
        if isinstance(node, ast.BinOp):
            if (
                classic
                and isinstance(node.op, ast.Pow)
                and isinstance(node.right, ast.BinOp)
                and isinstance(node.right.op, ast.Pow)
                and "("
                not in source[
                    getattr(node.left, "end_col_offset", 0) : node.right.col_offset
                ]
            ):
                operands = [node.left]
                part = node.right
                while isinstance(part, ast.BinOp) and isinstance(part.op, ast.Pow):
                    if (
                        "("
                        in source[
                            getattr(part.left, "end_col_offset", 0) : getattr(
                                part.right, "col_offset", 0
                            )
                        ]
                    ):
                        break
                    operands.append(part.left)
                    part = part.right
                operands.append(part)
                folded = operands[0]
                for operand in operands[1:]:
                    folded = ast.BinOp(left=folded, op=ast.Pow(), right=operand)
                return walk(folded)
            left, right = walk(node.left), walk(node.right)
            if isinstance(node.op, ast.Add):
                return left + right
            if isinstance(node.op, ast.Sub):
                return left - right
            if isinstance(node.op, ast.Mult):
                return left * right
            if isinstance(node.op, ast.Div):
                if right == 0:
                    raise EvalError("DIVIDE BY 0")
                return left / right
            if isinstance(node.op, ast.Pow):
                if isinstance(left, sp.MatrixBase):
                    if right.is_Integer is not True or not -1 <= right <= 3:
                        raise EvalError("Exponent must be Integer")
                    if left.rows != left.cols:
                        raise EvalError("DIM MISMATCH")
                    if right == -1 and left.det() == 0:
                        raise EvalError("SINGULAR MAT")
                    return left ** int(right)
                if left.free_symbols or right.free_symbols:
                    return left**right
                if (left == 0 and right == 0) or (
                    left.is_real is True and left < 0 and right.is_Integer is not True
                ):
                    raise EvalError("DOMAIN")
                if right.is_real is not True or abs(right) > 1000:
                    raise EvalError("Exponent must be real and between -1000 and 1000")
                if left == 0 and right < 0:
                    raise EvalError("Division by zero")
                # Bound output size as well as exponent size.
                magnitude = abs(complex(sp.N(left)))
                if magnitude and abs(float(right)) * abs(math.log10(magnitude)) > 4000:
                    raise EvalError("Power result is too large")
                return left**right
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and not node.keywords
        ):
            name = node.func.id
            if name not in FUNCTIONS:
                raise EvalError(f"Unknown function: {name}")
            args = [walk(arg) for arg in node.args]
            arity = (
                0
                if name == "rand"
                else (
                    2
                    if name
                    in {
                        "root",
                        "ncr",
                        "npr",
                        "randint",
                        "lcm",
                        "gcd",
                        "round",
                        "min",
                        "max",
                        "mod",
                        "polar",
                        "rx",
                        "ry",
                        "pr",
                        "pt",
                        "DotP",
                        "CrossP",
                    }
                    else 1
                )
            )
            if len(args) != arity:
                raise EvalError(f"{name} expects {arity} argument(s)")
            if name in {"sin", "cos", "tan"}:
                return getattr(sp, name)(args[0] * scale)
            if name in {"det", "transpose", "ref", "rref", "DotP", "CrossP", "norm"}:
                if not all(isinstance(arg, sp.MatrixBase) for arg in args):
                    raise EvalError("DATA TYPE")
                if name == "det":
                    return args[0].det()
                if name == "transpose":
                    return args[0].T
                if name == "ref":
                    return args[0].echelon_form()
                if name == "rref":
                    return args[0].rref()[0]
                if name == "DotP":
                    return args[0].dot(args[1])
                if name == "CrossP":
                    return args[0].cross(args[1])
                if name == "norm":
                    return args[0].norm()
            if name in {"asin", "acos", "atan"}:
                if (
                    name != "atan"
                    and not args[0].free_symbols
                    and (args[0].is_real is not True or abs(args[0]) > 1)
                ):
                    raise EvalError("DOMAIN")
                return getattr(sp, name)(args[0]) / scale
            if name in {"deg", "rad", "grad"}:
                return (
                    args[0]
                    * {"deg": sp.pi / 180, "rad": sp.S.One, "grad": sp.pi / 200}[name]
                    / scale
                )
            if name in {"rx", "ry"}:
                return args[0] * (sp.cos if name == "rx" else sp.sin)(args[1] * scale)
            if name == "pr":
                return sp.sqrt(args[0] ** 2 + args[1] ** 2)
            if name == "pt":
                return sp.atan2(args[1], args[0]) / scale
            if name == "polar":
                return args[0] * (
                    sp.cos(args[1] * scale) + sp.I * sp.sin(args[1] * scale)
                )
            if name == "angle":
                return sp.arg(args[0]) / scale
            if name == "square":
                return args[0] ** 2
            if name == "inverse":
                if isinstance(args[0], sp.MatrixBase):
                    if args[0].rows != args[0].cols:
                        raise EvalError("DIM MISMATCH")
                    if args[0].det() == 0:
                        raise EvalError("SINGULAR MAT")
                    return args[0].inv()
                if args[0] == 0:
                    raise EvalError("DIVIDE BY 0")
                return 1 / args[0]
            if name == "percent":
                return args[0] / 100
            if name in {"lcm", "gcd"}:
                a, b = [bounded_integer(arg, "Operand", 10**10) for arg in args]
                return sp.Integer(getattr(math, name)(a, b))
            if name in {"iPart", "fPart", "int"}:
                integer = (
                    sp.floor(args[0])
                    if name == "int"
                    else sp.sign(args[0]) * sp.floor(abs(args[0]))
                )
                return args[0] - integer if name == "fPart" else integer
            if name in {"min", "max"}:
                return (sp.Min if name == "min" else sp.Max)(*args)
            if name == "round":
                places = bounded_integer(args[1], "Decimal places", 9)
                return (
                    sp.sign(args[0])
                    * sp.floor(abs(args[0]) * 10**places + sp.Rational(1, 2))
                    / 10**places
                )
            if name == "mod":
                if args[1] == 0:
                    raise EvalError("DIVIDE BY 0")
                return sp.Mod(*args)
            if name == "root":
                degree = bounded_integer(args[0], "Root degree", 100)
                if degree == 0:
                    raise EvalError("Root degree must be positive")
                if args[1].is_real is True and args[1] < 0 and degree % 2 == 0:
                    raise EvalError("DOMAIN")
                return (
                    sp.real_root(args[1], degree)
                    if degree % 2
                    else sp.root(args[1], degree)
                )
            if name == "factorial":
                return sp.factorial(bounded_integer(args[0], "Factorial operand", 69))
            if name in {"ncr", "npr"}:
                n = bounded_integer(args[0], "n")
                r = bounded_integer(args[1], "r")
                if r > n:
                    raise EvalError("r must not exceed n")
                return (
                    sp.binomial(n, r)
                    if name == "ncr"
                    else sp.factorial(n) / sp.factorial(n - r)
                )
            if name == "rand":
                import random

                return sp.Rational(str((rng or random).random()))
            if name == "randint":
                import random

                a, b = [int(arg) for arg in args]
                if any(arg.is_Integer is not True for arg in args) or a > b:
                    raise EvalError("DOMAIN")
                return sp.Integer((rng or random).randint(a, b))
            if name in {"ln", "log", "sqrt"} and not args[0].free_symbols:
                if (
                    args[0].is_real is not True
                    or args[0] < 0
                    or (name != "sqrt" and args[0] == 0)
                ):
                    raise EvalError("DOMAIN")
            function = {
                "ln": sp.log,
                "log": lambda x: sp.log(x, 10),
                "abs": sp.Abs,
                "conj": sp.conjugate,
                "real": sp.re,
                "imag": sp.im,
            }.get(name)
            return (function or getattr(sp, name))(*args)
        raise EvalError(
            "Use only calculator numbers, operators, variables, and functions"
        )

    try:
        result = walk(tree.body)
        if result.has(sp.zoo, sp.oo, -sp.oo, sp.nan):
            raise EvalError("Math error: result is undefined")
        if isinstance(result, sp.MatrixBase):
            return result.applyfunc(sp.simplify)
        if not result.free_symbols:
            if (
                result.is_real is False
                and complex_format == "REAL"
                and not re.search(r"\bi\b", source)
            ):
                raise EvalError("DOMAIN")
            magnitude = sp.N(abs(result), 15)
            if magnitude >= 10**100 or (
                magnitude != 0 and magnitude < sp.Rational("1e-99")
            ):
                raise EvalError("OVERFLOW")
        return sp.simplify(result)
    except (TypeError, OverflowError, RecursionError) as exc:
        raise EvalError("Expression cannot be evaluated") from exc
